import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "OSS",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextUIProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </NextUIProvider>
  );
}
